import type { GolfLevel } from './golf.js';

/**
 * Campaña original «Parque Fantasía»: 10 hoyos con dificultad progresiva.
 * Los niveles 1, 2, 4, 6 y 10 están diseñados con una ruta válida de hoyo en uno.
 * Todos los trazados, nombres y elementos son originales.
 */
export const GOLF_LEVELS: GolfLevel[] = [
  {
    id: 1,
    name: 'Primer golpe',
    theme: 'Entrada del parque',
    difficulty: 'Fácil',
    par: 2,
    aceRoute: true,
    hint: 'Trayectoria recta con una pendiente muy suave. Ajusta la potencia.',
    size: { w: 940, h: 300 },
    start: { x: 130, y: 150 },
    hole: { x: 800, y: 150 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 90, w: 800, h: 120 }, surface: 'green', accel: { x: 6, y: 0 } },
    ],
    walls: [],
    circles: [],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 2,
    name: 'Rebote amistoso',
    theme: 'Paseo de las farolas',
    difficulty: 'Fácil',
    par: 2,
    aceRoute: true,
    hint: 'La banda diagonal del fondo desvía la bola hacia el pasillo del hoyo.',
    size: { w: 940, h: 640 },
    start: { x: 130, y: 500 },
    hole: { x: 556, y: 205 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 420, w: 540, h: 140 }, surface: 'green' },
      { id: 'p2', rect: { x: 460, y: 140, w: 140, h: 280 }, surface: 'green' },
    ],
    walls: [{ id: 'w-diag', a: { x: 500, y: 560 }, b: { x: 600, y: 460 }, restitution: 0.82 }],
    circles: [],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 3,
    name: 'Curva del jardín',
    theme: 'Jardín de setos',
    difficulty: 'Fácil-media',
    par: 3,
    aceRoute: false,
    hint: 'La arena frena mucho la bola. Encadena golpes cortos y controlados.',
    size: { w: 940, h: 640 },
    start: { x: 120, y: 510 },
    hole: { x: 450, y: 230 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 440, w: 300, h: 140 }, surface: 'green' },
      { id: 'p2', rect: { x: 360, y: 440, w: 180, h: 140 }, surface: 'sand' },
      { id: 'p3', rect: { x: 540, y: 300, w: 140, h: 280 }, surface: 'green' },
      { id: 'p4', rect: { x: 400, y: 160, w: 280, h: 140 }, surface: 'green' },
    ],
    walls: [],
    circles: [{ id: 'c1', pos: { x: 620, y: 400 }, radius: 16, restitution: 0.9, kind: 'rock' }],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 4,
    name: 'El molino',
    theme: 'Molino de viento',
    difficulty: 'Media',
    par: 2,
    aceRoute: true,
    hint: 'Cruza cuando las aspas estén tumbadas. El pasillo inferior rodea el molino.',
    size: { w: 940, h: 480 },
    start: { x: 140, y: 165 },
    hole: { x: 800, y: 165 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 120, w: 820, h: 180 }, surface: 'green' },
      { id: 'p2', rect: { x: 320, y: 300, w: 340, h: 120 }, surface: 'green' },
    ],
    walls: [],
    circles: [],
    blades: [
      {
        id: 'mill',
        center: { x: 470, y: 210 },
        armLength: 78,
        armRadius: 9,
        arms: 2,
        angularSpeed: 1.9,
        phase: 0,
        restitution: 0.55,
      },
    ],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 5,
    name: 'Caminos divididos',
    theme: 'Bifurcación del bosque',
    difficulty: 'Media',
    par: 3,
    aceRoute: false,
    hint: 'El atajo estrecho tiene parachoques. El camino inferior es largo pero seguro.',
    size: { w: 940, h: 640 },
    start: { x: 120, y: 400 },
    hole: { x: 760, y: 330 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 260, w: 220, h: 320 }, surface: 'green' },
      { id: 'p2', rect: { x: 280, y: 300, w: 320, h: 60 }, surface: 'green' },
      { id: 'p3', rect: { x: 280, y: 400, w: 140, h: 180 }, surface: 'green' },
      { id: 'p4', rect: { x: 420, y: 400, w: 60, h: 180 }, surface: 'sand' },
      { id: 'p5', rect: { x: 480, y: 400, w: 120, h: 180 }, surface: 'green' },
      { id: 'p6', rect: { x: 600, y: 260, w: 280, h: 320 }, surface: 'green' },
    ],
    walls: [],
    circles: [
      { id: 'b1', pos: { x: 380, y: 330 }, radius: 13, restitution: 1, kind: 'bumper' },
      { id: 'b2', pos: { x: 500, y: 330 }, radius: 13, restitution: 1, kind: 'bumper' },
    ],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 6,
    name: 'Salto de la cantera',
    theme: 'Cantera abandonada',
    difficulty: 'Media',
    par: 2,
    aceRoute: true,
    hint: 'La rampa necesita velocidad. Si te quedas corto, caerás a la red inferior.',
    size: { w: 940, h: 480 },
    start: { x: 130, y: 210 },
    hole: { x: 720, y: 190 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 120, w: 340, h: 180 }, surface: 'green' },
      { id: 'p2', rect: { x: 60, y: 300, w: 340, h: 120 }, surface: 'green' },
      { id: 'net', rect: { x: 400, y: 300, w: 200, h: 120 }, surface: 'sand' },
      { id: 'p3', rect: { x: 600, y: 120, w: 280, h: 300 }, surface: 'green' },
    ],
    walls: [],
    circles: [],
    blades: [],
    ramps: [
      {
        id: 'jump',
        rect: { x: 330, y: 120, w: 70, h: 180 },
        dir: { x: 1, y: 0 },
        minSpeed: 300,
        flightTime: 0.62,
        boost: 1,
      },
    ],
    checkpoints: [],
    respawnZones: [
      { id: 'pit', rect: { x: 400, y: 120, w: 200, h: 180 }, respawn: { x: 500, y: 360 } },
    ],
  },
  {
    id: 7,
    name: 'Puentes inquietos',
    theme: 'Pasarelas flotantes',
    difficulty: 'Media-alta',
    par: 4,
    aceRoute: false,
    hint: 'Las plataformas se mueven y la barrera se abre. Todo es cuestión de sincronización.',
    size: { w: 940, h: 640 },
    start: { x: 130, y: 330 },
    hole: { x: 790, y: 330 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 240, w: 220, h: 180 }, surface: 'green', open: ['right'] },
      {
        id: 'plat1',
        rect: { x: 300, y: 300, w: 130, h: 70 },
        surface: 'stone',
        floating: true,
        motion: { offset: { x: 0, y: -150 }, period: 4.4, phase: 0 },
      },
      {
        id: 'plat2',
        rect: { x: 470, y: 190, w: 130, h: 70 },
        surface: 'stone',
        floating: true,
        motion: { offset: { x: 0, y: 240 }, period: 5.2, phase: 1.3 },
      },
      { id: 'p2', rect: { x: 660, y: 240, w: 220, h: 180 }, surface: 'green', open: ['left'] },
    ],
    walls: [
      {
        id: 'gate',
        a: { x: 645, y: 240 },
        b: { x: 645, y: 420 },
        restitution: 0.6,
        motion: { offset: { x: 0, y: -200 }, period: 3.4, phase: 0 },
      },
    ],
    circles: [],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 8,
    name: 'Caverna helada',
    theme: 'Gruta de cristal',
    difficulty: 'Difícil',
    par: 4,
    aceRoute: false,
    hint: 'Hielo puro: casi no hay fricción y las bandas devuelven mucha energía.',
    size: { w: 940, h: 640 },
    wallRestitution: 0.88,
    start: { x: 110, y: 510 },
    hole: { x: 810, y: 470 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 460, w: 300, h: 100 }, surface: 'ice' },
      { id: 'p2', rect: { x: 260, y: 220, w: 100, h: 240 }, surface: 'ice' },
      { id: 'p3', rect: { x: 260, y: 140, w: 420, h: 80 }, surface: 'ice' },
      { id: 'p4', rect: { x: 580, y: 220, w: 100, h: 300 }, surface: 'ice' },
      { id: 'p5', rect: { x: 680, y: 420, w: 200, h: 100 }, surface: 'ice' },
    ],
    walls: [],
    circles: [
      { id: 'r1', pos: { x: 460, y: 180 }, radius: 15, restitution: 0.95, kind: 'rock' },
      { id: 'r2', pos: { x: 630, y: 330 }, radius: 12, restitution: 0.95, kind: 'rock' },
    ],
    blades: [],
    ramps: [],
    checkpoints: [],
    respawnZones: [],
  },
  {
    id: 9,
    name: 'Torre espiral',
    theme: 'Torre del reloj',
    difficulty: 'Muy difícil',
    par: 5,
    aceRoute: false,
    hint: 'Sube en espiral. El punto de control del tramo alto evita repetirlo todo.',
    size: { w: 940, h: 700 },
    start: { x: 110, y: 610 },
    hole: { x: 600, y: 470 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 560, w: 820, h: 100 }, surface: 'green' },
      { id: 'p2', rect: { x: 780, y: 160, w: 100, h: 400 }, surface: 'green' },
      { id: 'p3', rect: { x: 200, y: 160, w: 580, h: 100 }, surface: 'green' },
      { id: 'p4', rect: { x: 200, y: 260, w: 100, h: 300 }, surface: 'green' },
      { id: 'p5', rect: { x: 300, y: 420, w: 120, h: 100 }, surface: 'green', open: ['right'] },
      { id: 'p6', rect: { x: 500, y: 420, w: 180, h: 100 }, surface: 'green', open: ['left'] },
    ],
    walls: [],
    circles: [],
    blades: [
      {
        id: 'gear1',
        center: { x: 640, y: 210 },
        armLength: 62,
        armRadius: 8,
        arms: 2,
        angularSpeed: 1.5,
        phase: 0.4,
        restitution: 0.6,
      },
      {
        id: 'gear2',
        center: { x: 250, y: 400 },
        armLength: 34,
        armRadius: 6,
        arms: 2,
        angularSpeed: -1.4,
        phase: 0,
        restitution: 0.6,
      },
    ],
    ramps: [],
    checkpoints: [
      { id: 'cp1', rect: { x: 600, y: 160, w: 180, h: 100 }, respawn: { x: 690, y: 210 } },
    ],
    respawnZones: [
      { id: 'gapE', rect: { x: 420, y: 420, w: 80, h: 100 }, respawn: { x: 350, y: 470 } },
    ],
  },
  {
    id: 10,
    name: 'Golpe maestro',
    theme: 'Gran final del parque',
    difficulty: 'Experto',
    par: 4,
    aceRoute: true,
    hint: 'Rebote, hielo y trampolín. Con la potencia exacta, el vuelo termina en el hoyo.',
    size: { w: 1000, h: 700 },
    start: { x: 110, y: 530 },
    hole: { x: 520, y: 250 },
    pads: [
      { id: 'p1', rect: { x: 60, y: 460, w: 300, h: 140 }, surface: 'green' },
      { id: 'p2', rect: { x: 360, y: 460, w: 300, h: 140 }, surface: 'ice' },
      { id: 'p3', rect: { x: 660, y: 200, w: 240, h: 400 }, surface: 'green' },
      { id: 'p4', rect: { x: 300, y: 200, w: 360, h: 120 }, surface: 'green' },
    ],
    walls: [
      { id: 'kick', a: { x: 300, y: 600 }, b: { x: 360, y: 520 }, restitution: 0.9 },
      {
        id: 'gate',
        a: { x: 658, y: 200 },
        b: { x: 658, y: 320 },
        restitution: 0.6,
        motion: { offset: { x: 0, y: -130 }, period: 3.6, phase: 0 },
      },
    ],
    circles: [{ id: 'rock', pos: { x: 780, y: 420 }, radius: 18, restitution: 0.9, kind: 'rock' }],
    blades: [],
    ramps: [
      {
        id: 'springboard',
        rect: { x: 580, y: 460, w: 80, h: 140 },
        dir: { x: 1, y: 0 },
        minSpeed: 240,
        flightTime: 0.92,
        boost: 1,
        launchDir: { x: -0.12, y: -1 },
      },
    ],
    checkpoints: [],
    respawnZones: [],
  },
];

export const GOLF_TOTAL_LEVELS = GOLF_LEVELS.length;
export const GOLF_ACE_LEVEL_IDS = GOLF_LEVELS.filter((l) => l.aceRoute).map((l) => l.id);

export function getGolfLevel(id: number): GolfLevel {
  const level = GOLF_LEVELS.find((l) => l.id === id);
  if (!level) throw new Error('Nivel de golf desconocido: ' + id);
  return level;
}
